title: Jacob Langley
logo: "Images/Portfolio Headshot.jpeg?raw=true"
description: > # your text below (remove <br> elements if you don't need line breaks)
  First description 
  Experienced Data Analyst with a demonstrated history of improving supply management operations. 
  Skilled in data extraction using SQL and data analysis using Python and R. Extensive knowledge 
  in generating meaningful data visualizations with Qlik and Tableau that are used to make 
  intelligent business decisions. Strongly motivated professional with a Master's Degree focused 
  in Chemical Engineering from Arizona State University. 
  <a href="https://www.linkedin.com/in/example/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
