title: Jacob Langley
logo: "Images/Portfolio Headshot.jpeg?raw=true"
description:  > 
  Experienced Data Analyst with a demonstrated history of improving supply management operations. 
  Skilled in data extraction using SQL and data analysis using Python and R.
  <br><br>
  Extensive knowledge in 
  generating meaningful data visualizations with Qlik and Tableau that are used to make intelligent 
  business decisions.
  <br><br>
  <a href="https://www.linkedin.com/in/jacob-langley-370a4686/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
